"use client";
import { useEffect, useState } from "react";
import type { Operacion } from "@/lib/schemas";
import { RegisterHarvest } from "@/components/register-harvest";
import { RescuePlan } from "@/components/rescue-plan";
import { ApprovalImpact } from "@/components/approval-impact";
import examples from "@/data/examples.json";
import { canNavigateTo, type WizardStep } from "@/lib/wizard";
type Session={step:WizardStep;operacion:Operacion|null;texto:string;compradorSeleccionado:string};
const key="agraria-wizard-v1";const steps:{id:WizardStep;label:string}[]=[{id:"register",label:"1. Registrar"},{id:"plan",label:"2. Plan"},{id:"impact",label:"3. Aprobación"}];
export default function HomePage(){const [step,setStep]=useState<WizardStep>("register"),[operacion,setOperacion]=useState<Operacion|null>(null),[texto,setTexto]=useState(examples.caso_demostracion.texto),[compradorSeleccionado,setCompradorSeleccionado]=useState(""),[apiLoading,setApiLoading]=useState(false),[ready,setReady]=useState(false);useEffect(()=>{try{const raw=sessionStorage.getItem(key);if(raw){const s=JSON.parse(raw) as Session;setStep(s.step);setOperacion(s.operacion);setTexto(s.texto);setCompradorSeleccionado(s.compradorSeleccionado)}}finally{setReady(true)}},[]);useEffect(()=>{if(ready)sessionStorage.setItem(key,JSON.stringify({step,operacion,texto,compradorSeleccionado}))},[ready,step,operacion,texto,compradorSeleccionado]);function change(s:WizardStep){if(!apiLoading){setStep(s);window.scrollTo({top:0,behavior:"smooth"})}}function reset(){sessionStorage.removeItem(key);setOperacion(null);setTexto(examples.caso_demostracion.texto);setCompradorSeleccionado("");change("register")}return <main className="min-h-screen px-4 py-8"><header className="mx-auto mb-8 flex max-w-5xl justify-between"><b>AgrarIA</b><nav>{steps.map(s=><button key={s.id} disabled={apiLoading||!canNavigateTo(step,s.id)} onClick={()=>change(s.id)} className="px-2">{s.label}</button>)}<button onClick={reset}>Reiniciar demo</button></nav></header>{step==="register"&&<RegisterHarvest texto={texto} onTextoChange={setTexto} onPlanReady={o=>{setOperacion(o as Operacion);change("plan")}} onLoadingChange={setApiLoading}/>} {step==="plan"&&operacion&&<RescuePlan operacion={operacion} onUpdated={setOperacion} onContinue={()=>change("impact")} onBack={()=>change("register")} compradorSeleccionado={compradorSeleccionado} onCompradorSeleccionado={setCompradorSeleccionado} onLoadingChange={setApiLoading}/>} {step==="impact"&&operacion&&<ApprovalImpact operacion={operacion} onUpdated={setOperacion} onRestart={reset} onReviewPlan={()=>change("plan")} onLoadingChange={setApiLoading}/>}</main>}
