"use client";
import { useState } from "react";
import type { Operacion } from "@/lib/schemas";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ToolTimeline } from "@/components/tool-timeline";
import { formatCurrency, formatKg } from "@/lib/utils";
type Props={operacion:Operacion;onUpdated:(op:Operacion)=>void;onContinue:()=>void;onBack:()=>void;compradorSeleccionado:string;onCompradorSeleccionado:(id:string)=>void;onLoadingChange:(loading:boolean)=>void};
export function RescuePlan({operacion,onUpdated,onContinue,onBack,compradorSeleccionado,onCompradorSeleccionado,onLoadingChange}:Props){const [loading,setLoading]=useState(false);const dist=operacion.distribucion;const selected=compradorSeleccionado||dist?.asignaciones[0]?.comprador_id||"";async function cancel(){if(!selected||loading)return;setLoading(true);onLoadingChange(true);try{const res=await fetch("/api/replan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operacion_id:operacion.id,comprador_id:selected})});const data=await res.json();if(!res.ok)throw new Error(data.error);onCompradorSeleccionado("");onUpdated(data.operacion)}finally{setLoading(false);onLoadingChange(false)}}return <section className="mx-auto w-full max-w-5xl space-y-6"><div><Badge>{operacion.modo==="openai"?"OpenAI activo":"Modo de respaldo local"}</Badge><h2 className="mt-2 text-3xl">Plan para {operacion.lote.producto_canonico}</h2><p className="text-[var(--muted-foreground)]">{operacion.lote.cantidad} {operacion.lote.unidad_original} · {operacion.lote.categoria}</p></div>{operacion.estado==="requiere_informacion"||operacion.estado==="sin_coincidencias"?<Card><CardHeader><CardTitle>{operacion.estado==="requiere_informacion"?"Se requiere información":"Sin comprador compatible"}</CardTitle><CardDescription>{operacion.explicacion}</CardDescription></CardHeader><CardContent>{operacion.acciones_alternativas.map(a=><p key={a}>{a}</p>)}</CardContent></Card>:dist&&<><div className="grid gap-4 md:grid-cols-3"><Metric label="Asignado" value={formatKg(dist.volumen_asignado_kg)}/><Metric label="Neto" value={formatCurrency(dist.ingreso_neto_total)}/><Metric label="Sin asignar" value={formatKg(dist.volumen_sin_asignar_kg)}/></div><Card><CardHeader><CardTitle>Distribución propuesta</CardTitle><CardDescription>{operacion.urgencia?.justificacion}</CardDescription></CardHeader><CardContent className="space-y-2">{dist.asignaciones.map(a=><div key={a.comprador_id} className="flex justify-between rounded border p-3"><span>{a.comprador_nombre} · {formatKg(a.kg_asignados)} · {a.match_tipo}</span><span>{formatCurrency(a.ingreso_neto)}</span></div>)}{operacion.estado!=="aprobada"&&<div className="flex gap-2"><select value={selected} onChange={e=>onCompradorSeleccionado(e.target.value)} disabled={loading}>{dist.asignaciones.map(a=><option key={a.comprador_id} value={a.comprador_id}>{a.comprador_nombre}</option>)}</select><Button variant="danger" onClick={cancel} disabled={loading||!selected}>Cancelar comprador</Button></div>}</CardContent></Card></>}<Card><CardHeader><CardTitle>Trazabilidad</CardTitle></CardHeader><CardContent><ToolTimeline traza={operacion.traza}/></CardContent></Card><div className="flex justify-between"><Button variant="outline" onClick={onBack} disabled={loading}>Volver a registrar</Button>{dist&&<Button onClick={onContinue} disabled={loading}>Ir a aprobación</Button>}</div></section>}
function Metric({label,value}:{label:string;value:string}){return <Card><CardHeader><CardDescription>{label}</CardDescription><CardTitle>{value}</CardTitle></CardHeader></Card>}
